import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Aktualisierung from "./komponenten/aktualisierung";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        {children}
        {/* Liegt im Layout und nicht in einer einzelnen Seite, damit die
            Prüfung genau einmal beim Programmstart läuft und nicht bei jedem
            Seitenwechsel innerhalb der Anwendung erneut. */}
        <Aktualisierung />
      </body>
    </html>
  );
}
